type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 180
function_parameter_count: 6
